### ISSUE TITLE
Load values from file - key-value objects

### ISSUE THREAD

**Issue by ranrsg** [cyclops-ui/cyclops#398]
**Describe the bug**
When using the `Load values from file` option in creation of new module object types are ignored.
No error message is displayed, and other types are loaded properly.

*I am using a basic Helm chart created using `helm create`

Object Example:
- values.schema.json
```
"podLabels": {
          "description": "Key-value Pod labaels",
          "type": "object"
      }
```
- values.yaml
```
podLabels: 
  test: "value"
```

**Screenshots**
![image](https://github.com/cyclops-ui/cyclops/assets/125865943/331e7f6b-b5b8-4672-b3a3-a07d79126665)

![image](https://github.com/cyclops-ui/cyclops/assets/125865943/d25b175f-83ee-49c7-a228-07dfcb6c989b)

**Additional Notes**
When using `cyctl create modules` with `--file` the modules is getting created with now issues.

**Comment by petar-cvit** [comment]
Hey @ranrsg, thanks for reporting. Will check it out and update here

**Comment by petar-cvit** [comment]
Hey @ranrsg, found the issue and fixed updating maps. The issue is that having a map defined like this requires some processing to match the UI components. This processing was [done when fetching initial template values](https://github.com/cyclops-ui/cyclops/blob/5f8144d7016906438fca7fac45cb2f0c4ca35088/cyclops-ui/src/components/pages/NewModule/NewModule.tsx#L309), but we didn't do it while fetching data from a file.

We plan to release the v0.8.1 of Cyclops, and this fix will most likely be included in the release after that.

**Comment by ranrsg** [comment]
Thanks @petar-cvit. Will wait for this release 🙏

**Comment by ranrsg** [comment]
@petar-cvit - I was trying to run with the fix loacally without success.  Still ignoring maps when importing from file.

**Comment by petar-cvit** [comment]
@ranrsg you can try installing v0.8.3. I tried it on that release, and it picked up the maps from the file.

```sh
kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/v0.8.3/install/cyclops-install.yaml && kubectl apply -f https://raw.githubusercontent.com/cyclops-ui/cyclops/v0.8.3/install/demo-templates.yaml
```

**Comment by ranrsg** [comment]
@petar-cvit perfect! Thanks!
