### ISSUE TITLE
Implement delete pod action

### ISSUE THREAD

**Issue by petar-cvit** [cyclops-ui/cyclops#538]
**Is your feature request related to a problem? Please describe.**

[PodTable](https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/components/k8s-resources/common/PodTable/PodTable.tsx) showing pods for Deployments, DaemonSets and StatefulSets has a column called actions with a menu. When expanded, the menu currently only has a button for checking pod logs.

<img width="1509" alt="Screenshot 2024-08-27 at 14 44 11" src="https://github.com/user-attachments/assets/ee7c4ba0-0805-446f-829f-6bee48026cf7">

The scope of the issue is to implement the delete functionality and add a button to the same menu. When the button is clicked there should be a confirm modal. When the deletion is confirmed, the UI should call the `/resources` backend endpoint with the delete method.

A similar button is implemented [here](https://github.com/cyclops-ui/cyclops/blob/af65091e12c2a44867013a39a7919586599aa433/cyclops-ui/src/components/pages/ModuleDetails.tsx#L1055).

**Comment by naineel1209** [comment]
Hi @petar-cvit , I would like to work on this one, could you please assign it to me?

**Comment by naineel1209** [comment]
hi @petar-cvit, had a small doubt for this issue -

do we want to trigger the parent component's useEffect to refetch the pod's data after we have sent a request to delete the pod (because it shows running for few moments) or just let the pod's data be refreshed after the regular interval of its parent component?

if we implement a trigger below image is the output we get after I click on delete pod button, which i think closely resembles to what actually is happening in behind the scenes

![image](https://github.com/user-attachments/assets/f0e48cb9-3cfb-4282-9b36-957497fb7ffe)

**Comment by petar-cvit** [comment]
@naineel1209 good question. You can try fetching the parent component data once a pod is deleted
